version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vuln-kb-backend
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/app/data
      - backend_logs:/app/logs
    environment:
      # Azure OpenAI Configuration
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT=${AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT:-text-embedding-ada-002}
      - AZURE_OPENAI_COMPLETIONS_DEPLOYMENT=${AZURE_OPENAI_COMPLETIONS_DEPLOYMENT:-gpt-4o}
      # Database Configuration
      - DATABASE_PATH=app/data/vulnerabilities.db
      - VECTOR_DB_PATH=app/data/vector_db
      # Scraper Configuration
      - SNYK_BASE_URL=${SNYK_BASE_URL:-https://security.snyk.io/vuln/pip/}
      - SCRAPER_PAGES_TO_FETCH=${SCRAPER_PAGES_TO_FETCH:-10}
      # API Configuration
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_PREFIX=/api
      - ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
      # Performance Configuration
      - WORKERS=${BACKEND_WORKERS:-1}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - vuln-kb-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vuln-kb-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - vuln-kb-network

volumes:
  backend_data:
    driver: local
  backend_logs:
    driver: local

networks:
  vuln-kb-network:
    driver: bridge