apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vuln-kb.fullname" . }}-backend
  labels:
    {{- include "vuln-kb.backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "vuln-kb.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.backend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        # Force pod restart on secret changes
        checksum/secret: {{ include (print $.Template.BasePath "/backend-secret.yaml") . | sha256sum }}
      labels:
        {{- include "vuln-kb.backend.selectorLabels" . | nindent 8 }}
        {{- with .Values.backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vuln-kb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: {{ include "vuln-kb.backend.image" . }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.backend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "vuln-kb.fullname" . }}-backend
          volumeMounts:
            {{- if .Values.backend.persistence.data.enabled }}
            - name: data
              mountPath: {{ .Values.backend.persistence.data.mountPath }}
            {{- end }}
            {{- if .Values.backend.persistence.logs.enabled }}
            - name: logs
              mountPath: {{ .Values.backend.persistence.logs.mountPath }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      volumes:
        {{- if .Values.backend.persistence.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "vuln-kb.fullname" . }}-backend-data
        {{- end }}
        {{- if .Values.backend.persistence.logs.enabled }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "vuln-kb.fullname" . }}-backend-logs
        {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}