apiVersion: v1
kind: Service
metadata:
  name: {{ include "vuln-kb.fullname" . }}-backend
  labels:
    {{- include "vuln-kb.backend.labels" . | nindent 4 }}
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vuln-kb.backend.selectorLabels" . | nindent 4 }}