# ================================================================
# BACKEND DEVELOPMENT ENVIRONMENT CONFIGURATION
# ================================================================
# This file contains development-specific overrides for the base values.yaml
# Usage: helm install backend . -f values.yaml -f values.dev.yaml

# -- Development namespace
namespace: backend-dev

# -- Single replica for development
replicaCount: 1

# -- Development image configuration
image:
  # -- Development registry and image
  repository: "mydevacr.azurecr.io/backend-dev"
  # -- Always pull latest for development
  pullPolicy: Always
  # -- Use development tag
  tag: "dev"

# -- Development resource limits (lower for cost optimization)
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

# -- Development environment variables
env:
  enabled: true
  variables:
    LOG_LEVEL: "debug"
    DEBUG: "true"
    APP_ENV: "development"
    PORT: "8000"
    PYTHONPATH: "/app"

# -- Relaxed health checks for development
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 10

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 5

# -- Disabled autoscaling for development
autoscaling:
  enabled: false

# -- Disabled PDB for development
podDisruptionBudget:
  enabled: false

# -- Development network policy (more permissive)
networkPolicy:
  enabled: true
  ingress:
    - from: []  # Allow all ingress in development
  egress:
    - to: []    # Allow all egress in development

# -- Development security (relaxed for debugging)
podSecurityStandards:
  enabled: true
  enforceBaseline: true
  enforceRestricted: false  # Relaxed for development

# -- Development compliance (disabled)
compliance:
  enabled: false

# -- Development resource governance (disabled)
resourceQuota:
  enabled: false

limitRange:
  enabled: false

# -- Development Azure integration
azureKeyVault:
  enabled: false  # Use local secrets in development

aks:
  workloadIdentity:
    enabled: false  # Use local identity in development
  topologySpreadConstraints:
    enabled: false  # No HA requirements in development