{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.serviceAccountName" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- $annotations := .Values.serviceAccount.annotations | default dict }}
  {{- if and .Values.aks.workloadIdentity.enabled .Values.aks.workloadIdentity.annotations }}
    {{- $annotations = merge $annotations .Values.aks.workloadIdentity.annotations }}
  {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
{{- if .Values.serviceAccount.automount }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- end }}